wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1656672580
    t:
      1:
      - 55
      4: 3.9.12
      5: 0.12.20
      8:
      - 5
